"""Create a portable presentation page from the recorded public result set."""
import html,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];MEDIA=ROOT/'docs/media'
r=json.loads((MEDIA/'real-results.json').read_text())
rows=[]
for book in r['results']:
 p=book['evaluation']['probabilities']; top=max(p['cat_'+c['id']] for c in r['categories'])
 status='Ready' if book['status']=='ready' else 'Review required'
 source='Metadata + EPUB excerpts' if book['source']=='content' else 'Metadata'
 values=[book['title'],', '.join(book['tags']),f'{top:.2f}',f'{p["evidence"]:.2f}',source,status]
 cells=''.join('<td>'+html.escape(v)+'</td>' for v in values)
 rows.append('<tr data-status="'+book['status']+'">'+cells+'</tr>')
page='''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>JEV Book Tags — real API demonstration</title>
<style>
:root{color-scheme:dark;--bg:#101c2c;--fg:#f4f7fb;--muted:#b3c1d0;--accent:#55dfc0;--line:#304258}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg);font:17px/1.65 system-ui,sans-serif}main{max-width:1180px;margin:auto;padding:64px 24px}a{color:var(--accent)}h1{font-size:clamp(34px,5vw,64px);line-height:1.1;max-width:950px;margin:14px 0 22px}h2{font-size:30px;margin:0 0 15px}.eyebrow{color:var(--accent);letter-spacing:.09em;font-size:14px;font-weight:700}p{max-width:920px}.muted{color:var(--muted)}section{margin-top:64px}video,img{display:block;width:100%;height:auto;border:1px solid var(--line);border-radius:12px}video{margin:26px 0 15px;background:#000}.links{display:flex;flex-wrap:wrap;gap:12px}.links a{padding:10px 16px;border:1px solid var(--line);border-radius:7px;text-decoration:none}.steps,.facts{display:grid;grid-template-columns:repeat(auto-fit,minmax(235px,1fr));gap:16px}.box{border:1px solid var(--line);padding:22px;border-radius:12px}.box h3{margin:0 0 12px}.box p{margin:0;color:var(--muted)}.metric{font-size:36px;font-weight:700;color:var(--accent)}label{display:block;margin:18px 0}select{margin-left:10px;padding:9px;background:#17263b;color:var(--fg);border:1px solid var(--line);border-radius:5px}.table-wrap{overflow:auto;border:1px solid var(--line);border-radius:10px}table{border-collapse:collapse;width:100%;font-size:15px}th,td{text-align:left;padding:13px 16px;border-bottom:1px solid var(--line)}th{color:var(--accent)}td:nth-child(1){min-width:260px}td:nth-child(2){min-width:190px}td:nth-child(5){min-width:175px}tr[hidden]{display:none}footer{border-top:1px solid var(--line);padding-top:22px;margin-top:64px;color:var(--muted);font-size:14px}
</style></head><body><main>
<header><div class="eyebrow">CALIBRE PLUGIN · POWERED BY TYPESAFE AI JEV</div><h1>Useful book tags.<br>You keep the final say.</h1><p class="muted">Classify one book, a selection, or an entire library. Define your categories, inspect the suggestions, and apply the tags you choose while preserving existing labels.</p></header>
<video controls preload="metadata" poster="media/01-intro.png"><source src="media/jev-book-tags-demo.mp4" type="video/mp4"><track kind="captions" src="media/demo.vtt" srclang="en" label="English">Your browser does not support video. <a href="media/jev-book-tags-demo.mp4">Download the video</a>.</video>
<p class="muted">76-second silent walkthrough with English explanations. Edited from native interface captures and real API results; it is not a continuous screen recording.</p>
<nav class="links" aria-label="Demo resources"><a href="https://github.com/iamjonatha/jev-book-tags">Plugin README</a><a href="media/jev-book-tags-demo.mp4" download>Download video</a><a href="media/jev-book-tags-demo.gif">Animated preview</a><a href="media/demo-categories-en.json" download>English categories</a></nav>
<section><h2>A reviewable workflow</h2><div class="steps"><div class="box"><h3>1. Configure</h3><p>Start with your API key and vocabulary. Expand advanced options to configure the model and thresholds.</p></div><div class="box"><h3>2. Review</h3><p>Click tags for one book, or filter the batch list and open book details. Uncertain rows stay unchecked.</p></div><div class="box"><h3>3. Apply</h3><p>Add selected tags while keeping manual labels. Export CSV results and restore eligible changes.</p></div></div></section>
<section><h2>What the real run returned</h2><div class="facts"><div class="box"><div class="metric">32</div><div>English-language books</div></div><div class="box"><div class="metric">31 / 1</div><div>ready / review required</div></div><div class="box"><div class="metric">0</div><div>API request errors</div></div><div class="box"><div class="metric">18</div><div>configured categories</div></div></div><p class="muted">Interface and decision rules: JEV Book Tags 1.1.1, calibre 9.13. Genuine JEV responses recorded on 1 October 2026 are reused unchanged; no new API calls were needed. Requested model: jev-latest; returned: jev-1.13.0. Global threshold: 85%; Programming override: 95%.</p><p>These are suggestions, not an accuracy benchmark. Each assigned category must reach its own threshold and evidence must be sufficient. Independent category scores do not sum to 100%. The complete run is shown below, including every review-required case.</p>
<label for="status">Show<select id="status"><option value="all">All 32 books</option><option value="ready">Ready for assignment</option><option value="review">Review required</option></select></label>
<div class="table-wrap"><table><thead><tr><th scope="col">Book</th><th scope="col">Suggested tags</th><th scope="col">Top score</th><th scope="col">Evidence</th><th scope="col">Input used</th><th scope="col">Decision</th></tr></thead><tbody>__ROWS__</tbody></table></div>
<p><a href="media/real-results.csv">Download CSV</a> · <a href="media/real-results.json">Download full probabilities and configuration</a></p></section>
<section><h2>From library selections to a single book</h2><p class="muted">The plugin menu supports the current book, selected books and the entire current library. The metadata-editor icon uses the current form; confirming with OK saves staged tags, while Cancel discards them. Its position is configurable.</p><a href="media/metadata-editor.png"><img src="media/05-editor.png" alt="Calibre's native metadata editor with the JEV Book Tags icon beside Tags, and the preserved manual tag plus Computing and Programming." loading="lazy"></a></section>
<section><h2>A threshold for one category</h2><p>Open <strong>Advanced options</strong>. Set the Programming category threshold to <strong>0.95 (95%)</strong>; empty cells inherit the global <strong>0.85 (85%)</strong>. Pro Git receives Programming with a genuine 98% score. The Linux Command Line scores 75% for Programming, so that tag is not assigned automatically.</p><img src="media/09-threshold.png" alt="Advanced settings with Programming selected and a category threshold of 0.95." loading="lazy"></section>
<section><h2>Clickable choices, clear review reasons</h2><img src="media/10-single.png" alt="Single-book classification with clickable tags." loading="lazy"><p>One book stays below threshold: Dr. Jekyll and Mr. Hyde. Review its suggested tags and confirm only the labels you choose.</p><img src="media/11-review-detail.png" alt="Review detail showing Mystery 84%, Horror 81%, Fiction 80%, all below the 85% threshold." loading="lazy"></section>
<section><h2>What stays under your control</h2><div class="steps"><div class="box"><h3>Input</h3><p>Send metadata only or add partial EPUB text. The full book file is not uploaded. PDF files use metadata.</p></div><div class="box"><h3>Vocabulary</h3><p>Write inclusion rules, set per-category thresholds, and import or export vocabularies and profiles.</p></div><div class="box"><h3>Application</h3><p>Review and edit proposed tags before applying them. Successful evaluations are cached for resume and retry.</p></div></div></section>
<footer>The media run used a separate library copy. A manual “Demo collection” tag was added only to that copy to verify preservation. No simulated decisions, API keys or book text are included in the public result files. Source code, releases and contributions are hosted on GitHub. See <a href="https://github.com/iamjonatha/jev-book-tags/blob/main/docs/DEMO.md">production notes and source credits</a>.</footer>
</main><script>document.getElementById('status').addEventListener('change',function(){document.querySelectorAll('tbody tr').forEach(row=>{row.hidden=this.value!=='all'&&row.dataset.status!==this.value;});});</script></body></html>
'''
rendered=page.replace('__ROWS__',''.join(rows))
(ROOT/'docs/demo.html').write_text(rendered)
(ROOT/'docs/index.html').write_text(rendered)
chapters=json.loads((MEDIA/'chapters.json').read_text())
def timestamp(t):return f'{t//3600:02}:{t//60%60:02}:{t%60:02}.000'
lines=['WEBVTT',''];time=0
for chapter in chapters:
 end=time+chapter['duration_seconds'];lines += [f'{timestamp(time)} --> {timestamp(end)}',chapter['title'],''];time=end
(MEDIA/'demo.vtt').write_text('\n'.join(lines).rstrip()+'\n')
print('Built presentation page: 32 rows, status filter, video and captions.')
